name: 'Terraform Validate and Plan'

on:
  push:
    branches:
      - '**'

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.0.0

    - name: Install tflint
      run: |
        curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | jq -r '.assets[] | select(.name | test("linux_amd64")) | .browser_download_url')" > tflint.zip
        unzip tflint.zip
        sudo mv tflint /usr/local/bin/tflint
        rm tflint.zip

    - name: Run tflint
      run: tflint

  terraform-validate:
    runs-on: ubuntu-latest
    needs: tflint

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.0.0

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-validate

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.0.0

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan